### ISSUE TITLE
RqHeaders must be an interface

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#136]
`RqHeaders` must be an interface and its implementation must be in its nested class `RqHeaders.Base`. Let's refactor it accordingly. The interface should look like:

```java
public interface RqHeaders extends Request {
  Iterable<String> header(String name);
  Iterable<String> names();
}
```

**Comment by davvd** [comment]
@yegor256 sure, thanks, I added bug tag to it

**Comment by davvd** [comment]
@yegor256 thank you for the ticket reported, I topped your account for 15 mins, transaction `000-d5b9dcee`

**Comment by davvd** [comment]
@lauresh this task is for you, keep [these principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions

The budget of this task is **30 mins**. This is exactly how much time will be compensated, when the task is completed. Read about our [Definition of Done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by lauresh** [comment]
@yegor256 I have question about Javadoc.

How can I understand release number (@since xxx) for my changes? Previous release version is 0.13.7 How can i understood next number (0.13.8 or 0.14)?

Thank you!

**Comment by yegor256** [comment]
@lauresh just look here and pick the next major version: https://github.com/yegor256/takes/releases

**Comment by davvd** [comment]
@lauresh you're working with this ticket for the last 15 days. If it is not closed within the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle. [This article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck; -30 to your rating, your total score is [-60](http://www.netbout.com/b/35288?open=rating)

**Comment by davvd** [comment]
@lauresh the task is overdue, and I have to re-assign it to someone else. Please, stop working with it immediately. In general, we're against overdue tasks, check [this page](http://www.xdsd.org/2014/04/13/no-obligations-principle.html); -60 to your rating, your total score is [-180](http://www.netbout.com/b/35288?open=rating)

**Comment by davvd** [comment]
@yamstranger please proceed,it's yours

**Comment by YamStranger** [comment]
@davvd  thanks

**Comment by YamStranger** [comment]
@davvd, @yegor256 ticket passed QA review.

**Comment by YamStranger** [comment]
@yegor256 please close this ticket. Thanks

**Comment by YamStranger** [comment]
@yegor256 @davvd please help me understand why this ticket is invalid, and why I was removed from this ticket?  Thanks

**Comment by yegor256** [comment]
@YamStranger was there any code written by yourself? if so, in what PR?

**Comment by YamStranger** [comment]
@yegor256  Not. I did not wrote any line on code on this ticket. But to be honest - this ticket was not closed, only because @elenavolokhova did not closed it, and did not marked as "passed review". So when @davvd assign it to me - my task was close this ticket. And as I understand, if ticket assign to me - now I become responsible for it, and can rise my rating on this ticket, or loos some points(as @lauresh ), also difficulty of task described in "30 mins" label, nothing else matters. Is it correct? on  And I closed it by writing all info, what @elenavolokhova expected. After this ticket become "ready for closing", @davvd described payment info  for @longtimeago and  @elenavolokhova, and I was just removed from this ticket, and it was marked as "invalid". You like rules, I like it too. So, according rules - please describe me - why I spend time to some ticket for closing it, and instead of any changing of  my rating  - it just become "invalid". P.S. I don't know what is "PR" means. I spend on this ticket 4 minutes.

**Comment by YamStranger** [comment]
@yegor256. As wrote @alice, I am not with your team any more. So, let finish this discussion. As I understand now - you pay only of code (of any project improvement), but not for "closing tickets". That is why this ticket was closed without adding any points for me. @yegor256 Is my understanding correct?
