### ISSUE TITLE
RqMethod must be an interface

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#137]
`RqMethod` must be an interface and its implementation must be in its nested class `RqMethod.Base`. Let's refactor it accordingly. The interface should look like:

```java
public interface RqMethod extends Request {
  String method();
}
```

**Comment by davvd** [comment]
@yegor256 got it, tag `bug` is here

**Comment by davvd** [comment]
@yegor256 thank you for the ticket reported, I topped your account for 15 mins, transaction `000-3d72e2c0`

**Comment by MohandAndel** [comment]
@davvd  I hope I have finally commit in the right way ! . I made a big mess with git until I had to reset everything and start over again . << this user is new to git world !

**Comment by davvd** [comment]
@dmzaytsev please go ahead with this task, it's yours

**Comment by dmzaytsev** [comment]
@yegor256 #177 is fixing this issue, please close  if that's all here, thank you

**Comment by yegor256** [comment]
@dmzaytsev thanks!

**Comment by davvd** [comment]
@yegor256 I added milestone `1.0` to this issue, let me know if there has to be something else

**Comment by davvd** [comment]
@elenavolokhova please, review this ticket for compliance with our [QA rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd This ticket looks good.

**Comment by davvd** [comment]
> @davvd This ticket looks good.

@elenavolokhova thanks for the review and a good remark

**Comment by davvd** [comment]
@dmzaytsev 10 mins was added to the account of @elenavolokhova (for QA review), in transaction 55985009; **1 hour** added to your account (payment number `55985089`), many thanks for your contribution! 68 hours and 36 mins spent here.; age=2, that's why a bonus here for fast delivery; +60 added to your rating, current score is: [+956](http://www.netbout.com/b/35166?open=rating)
