### ISSUE TITLE
XeAppend extra ctor

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#147]
Extra ctor is required for `XeAppend`, which would allow to pass an `Iterable` of sources.

**Comment by yegor256** [comment]
@rultor release, tag is `0.12.4`

**Comment by davvd** [comment]
@yegor256 the task is yours (budget is 30 mins)

**Comment by davvd** [comment]
@elenavolokhova please, review this ticket for compliance with our [QA rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@yegor256 
 According to our [quality rules](http://www.teamed.io/qa.html):
 >Problem reporter and problem solver are two different persons.
 
 This was not a case in this ticket. Please avoid fixing your own issues.
 
 Please confirm that everything is clear and you have no questions regarding this approach.

**Comment by yegor256** [comment]
@elenavolokhova yeah, I got it, thanks

**Comment by elenavolokhova** [comment]
@yegor256 Thank you!

**Comment by elenavolokhova** [comment]
@davvd Ticket passed QA review. Quality is acceptable.

**Comment by davvd** [comment]
> @davvd Ticket passed QA review. Quality is acceptable.

@elenavolokhova thanks for the review, we'll try better next time

**Comment by davvd** [comment]
@yegor256 just added 10 mins to @elenavolokhova (for QA), payment ID is `55578628`... Many thanks! **1 hour** were added to your account in Transaction ID `000-28d787bd` (task took 10 hours and 30 mins)... age=7, that's why a bonus here for fast delivery... +60 added to your rating, current score is: [+9017](http://www.netbout.com/b/35008?open=rating)
