### ISSUE TITLE
RqLengthAware doesn't intercept the other two read() methods

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#206]
At the moment, `RqLengthAware` doesn't intercept the other two `read()` methods, but it should. It should override them and make sure calls to them also decrease the internal length counter.

**Comment by davvd** [comment]
@yegor256 we will find someone to do this task, soon

**Comment by davvd** [comment]
@yegor256 milestone set to `1.0` (correct me if I am wrong)

**Comment by davvd** [comment]
@dmzaytsev the task is yours,please go ahead

**Comment by davvd** [comment]
@yegor256 thanks a lot for reporting, **15 mins** added to your acc, pmt ID `000-db3fd47a`

**Comment by dmzaytsev** [comment]
@davvd the PR for this task here  #208 
please  find someone who can review this pull request

**Comment by dmzaytsev** [comment]
@yegor256 take a look the PR #208 
please close  if that's all here, thank you

**Comment by yegor256** [comment]
@dmzaytsev thanks!

**Comment by davvd** [comment]
@elenavolokhova please, let us know what do you think about this ticket, according to our [QA rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd Looks good!

**Comment by davvd** [comment]
> @davvd Looks good!

@elenavolokhova thanks!

**Comment by davvd** [comment]
@dmzaytsev just added 10 mins to @elenavolokhova (for QA), payment ID is `56414325`. **38 mins** was added to your account, many thanks for your contribution! The task took 56414330.. age=58 hours and 2 mins, that's why a bonus here for fast delivery. added +38 to your rating, now it is equal to [+1107](http://www.netbout.com/b/35166?open=rating)
