### ISSUE TITLE
Class naming

### ISSUE THREAD

**Issue by bandrzejczak** [yegor256/takes#34]
I'd like to know what was your motivation for naming your classes. I know, that when someone will use your framework for a while will get to know all the prefixes, but for me all the Tk*, Rq*, Ts* mean nothing and are just something that makes the learning curve more steep. Is there some greater intent in ignoring all the good practices against abbreviations in names?

**Comment by yegor256** [comment]
@bandrzejczak well, here is the logic. We have a few interfaces in the framework: `Takes`, `Take`, `Request`, `Response`, `Fork`, `Codec`, etc. And we have many classes that implement them. 17 classes implement `Takes`, for example, see http://www.takes.org/apidocs-0.8.4/org/takes/Takes.html Naming them all like `TakesFiles`, `TakesFallback`, `TakesFailure`, `TakesFork` is just too verbose. This `Takes` prefix is just too long to stay everywhere in all classes. I think it's more compact and elegant to shorten it to `Ts`. And I believe it's a good practice to do this in all other situations.

So, I don't think these "good practices" are actually good. When I see class names from Spring I find them very ugly. I believe that a class name should be a noun, with a possible prefix, in order to help to distinguish nouns in the entire Java scope.

Do I make sense?

**Comment by bandrzejczak** [comment]
@yegor256 Yes, you do make sense. You don't use compound names (after stripping the prefix), so honestly I wouldn't mind the class name to be `TakesFiles` or `TakesFallback`.

I don't think, that prefixes in class names can discourage anybody from using the framework, so as long as they help see through packaging and interfaces the class are implementing it's pretty fine.

Thanks for the explanation.
