### ISSUE TITLE
PsCookie is not tested

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#38]
There is no unit test for `PsCookie` class, let's create one

**Comment by davvd** [comment]
@yegor256 right, I added the `bug` tag

**Comment by davvd** [comment]
@yegor256 thank you for reporting this, I added 15 mins to your acc, transaction `000-7acea403`

**Comment by davvd** [comment]
@dmzaytsev this task is for you, keep [these principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions; The budget of this issue is **30 mins**, which is exactly how much will be paid when the task is *done* (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by dmzaytsev** [comment]
@yegor256 @davvd 
unit test for PsCookie already exists
https://github.com/yegor256/takes/blob/master/src/test/java/org/takes/facets/auth/PsCookieTest.java

**Comment by yegor256** [comment]
@dmzaytsev right, no need to do this
