### ISSUE TITLE
BkWrap

### ISSUE THREAD

**Issue by hs3180** [yegor256/takes#399]
`BkParallel`, `BkSafe` and `BkTimeable` wrap a `Back` object and pass socket to it.
These three object share this same feature which can be abstracted like `RsWrap`, `RqWrap`, `TkWrap`

**Comment by yegor256** [comment]
@hs3180 good point, thanks!

**Comment by davvd** [comment]
@hs3180 I am aware of the task, give me some time to find a developer...

**Comment by davvd** [comment]
@hs3180 there is no milestone yet, so I set it to `1.0`

**Comment by davvd** [comment]
@hs3180 thanks for the ticket, your account was topped for 15 mins, payment AP-156125656A123613M

**Comment by davvd** [comment]
@hdouss it's yours now, please proceed keeping in mind [our principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Feel free to ask any technical questions right here in the ticket

The budget of this issue is **30 mins**, which is exactly how much will be paid when the task is *done* (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by HDouss** [comment]
@hs3180 PR #452 has been merged to master. The issue can be closed.

**Comment by HDouss** [comment]
@hs3180 PR #452 merged and reviewed. Please close the issue.

**Comment by hs3180** [comment]
@HDouss thanks.

**Comment by davvd** [comment]
@elenavolokhova review this ticket please, for compliance with our [quality rules](http://at.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@davvd Looks good!

**Comment by davvd** [comment]
> @davvd Looks good!

@elenavolokhova thank you

**Comment by davvd** [comment]
@hdouss added 10 mins to @elenavolokhova, for QA review, payment code is `71896197`; Many thanks! **30 mins** were added to your account in Transaction ID `71896205` (task took 143 hours and 6 mins); +30 added to your rating, at the moment it is: [+135](http://www.netbout.com/b/36032?open=rating)
