### ISSUE TITLE
Identity.Simple#properties() is already an unmodifiable map

### ISSUE THREAD

**Issue by simonjenga** [yegor256/takes#423]
In ```org.takes.facets.auth.Identity.Simple``` the variable 

```private final transient Map<String, String> props;```

has already been initialized to an unmodifiable view of the specified map  in the class constructor using,

```this.props = Collections.unmodifiableMap(map);```

The following method needs to be changed to prevent a redundant method call in the return statement as follows:

```
@Override
public Map<String, String> properties() {
    return this.props;
}
```

It is currently implemented as ```return Collections.unmodifiableMap(this.props);```

**Comment by davvd** [comment]
@yegor256 dispatch this issue please, see [par.21](http://www.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@simonjenga this is done intentionally. These two decorating are the in order to prevent two different kinds of mistakes. We want to encapsulate only unmodifiable map in order to prevent modifications to it. And, we want to return unmodifiable map in order to prohibit any changes to it from outside.
