### ISSUE TITLE
TkFallback is not tested

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#45]
There is no unit test for `TkFallback` class, let's create one.

**Comment by davvd** [comment]
@yegor256 thanks, I added the "bug" tag

**Comment by davvd** [comment]
@yegor256 thank you for the ticket reported, I topped your account for 15 mins, transaction `000-15e57ecd`

**Comment by davvd** [comment]
@andrewbol please go ahead, it's your task now, keep [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions you may have

This task's budget is **30 mins**. This is exactly how much will be paid when the problem explained above is solved. See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by yegor256** [comment]
@davvd assign someone else pls

**Comment by davvd** [comment]
> @davvd assign someone else pls

@yegor256 all right, we'll find someone else for this task

**Comment by davvd** [comment]
@dmzaytsev can you please help? Keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If you have any technical questions, don't hesitate to ask right here

The budget of this issue is **30 mins**, which is exactly how much will be paid when the task is *done* (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by dmzaytsev** [comment]
@yegor256 the PR has been merged
close the issue please

**Comment by yegor256** [comment]
@dmzaytsev thanks!

**Comment by davvd** [comment]
@dmzaytsev I just added **30 mins** to your account, many thanks for your contribution.. 54223443 spent here

+30 added to your rating, current score is: [+105](http://www.netbout.com/b/35166?open=rating)
