### ISSUE TITLE
Improve Javadoc in RsFlash

### ISSUE THREAD

**Issue by mkordas** [yegor256/takes#540]
I see couple of improvements that could be made for users of `RsFlash` class in [its Javadoc](http://www.takes.org/apidocs-0.27/org/takes/facets/flash/RsFlash.html):
* describe better what is "flash mechanism"
* provide more description than just "Ctor."  for constructors with `Throwable` - focus mainly on how exception will be converted to text
* Provide information why it's better to use default cookie name
* Fix the code samples in Javadoc - they are confusing and not compilable

**Comment by davvd** [comment]
@yegor256 take a look at this issue please and dispatch it somehow, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by davvd** [comment]
@mkordas since there is no milestone yet I set it to "1.0"

**Comment by davvd** [comment]
@mkordas thanks for this report, I added 15 mins to your account, in transaction `56aca57efdc2bb2698000275`

**Comment by davvd** [comment]
@essobedo this task is yours, please help (see our key [principles of work](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html)). If you have any technical questions, don't hesitate to ask right here

**30 mins** is the budget of the task. This is exactly how much will be paid when the problem is [solved](http://www.xdsd.org/2014/04/15/definition-of-done.html) (no matter how much time you will actually spend). See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by essobedo** [comment]
@mkordas Please have look to my https://github.com/yegor256/takes/pull/563 and close the ticket if it is what you exepected

**Comment by mkordas** [comment]
@essobedo can you as some more details? About how this works in practice and when it should not be used.

**Comment by essobedo** [comment]
@mkordas do you talk about the cookie name? If so I removed it because for me it doesn't make any sense to implement something and say don't use it because it is not recommended. Either you remove the feature because nobody will use it as it is not recommended or you keep it assuming that users know what they are doing.

**Comment by essobedo** [comment]
@mkordas if you don't have any remarks, please close the ticket

**Comment by mkordas** [comment]
@essobedo I was not talking about cookie name. I rather meant that we could state that RsFlash should not be used for other purposes than displaying flash message. E.g. it should not be used in pure REST interface.

**Comment by essobedo** [comment]
@mkordas sorry but for me it is out of the original topic, it should be another ticket. IMHO you cannot change the request once I produced the PR, otherwise it is unfair and potentially endless. Please don't forget that it is supposed to be a "30 minutes task".
@davvd What are we supposed to do in that case? Create a new ticket or continue with this one?

**Comment by mkordas** [comment]
@essobedo it's too small thing for a new ticket, such ticket would be rejected. As you said ticket resolution should take 30 min, not 3 min. And you've asked about my opinion, so I provided it, but it is not a blocker.

**Comment by mkordas** [comment]
@essobedo BTW, pull request is not merged, why you want from me to close the ticket?

**Comment by essobedo** [comment]
@mkordas My bad, I guess you are right, I'm just unaware of the workflow. I've just read somewhere that I had to ask the ticket owner to close the ticket once done, it is obviously not the way it works

**Comment by essobedo** [comment]
@mkordas Here is what I added https://github.com/essobedo/takes/commit/c1c11aa7b15a3a035bb73bf36e1c51b2f92732a6, I hope it is what you wanted

**Comment by essobedo** [comment]
@mkordas thank you for your feedback, here is a new PR https://github.com/yegor256/takes/pull/570 with your remarks

**Comment by mkordas** [comment]
@essobedo please update both PR descriptions with `For #540`. Only then GitHub will create links here.

**Comment by essobedo** [comment]
@mkordas Thx for your remark, I added "For #{tciket-id}" in all my PR descriptions even old ones

**Comment by essobedo** [comment]
@davvd The PR has been merged what is the next step now? who is supposed to close the ticket?

**Comment by mkordas** [comment]
@essobedo author must close the ticket, thanks

**Comment by essobedo** [comment]
@mkordas thank you for the info

**Comment by essobedo** [comment]
@davvd What is the next step knowing that the ticket is closed now?

**Comment by davvd** [comment]
@ypshenychka please, check this issue for QA compliance, as per [par.24](http://at.teamed.io/policy.html#24)

**Comment by ypshenychka** [comment]
@davvd Quality is good here.

**Comment by davvd** [comment]
> @davvd Quality is good here.

@ypshenychka thanks for the review and a good remark

**Comment by davvd** [comment]
@essobedo added 10 mins to @ypshenychka, for QA review, payment code is `77116007`... Thanks a lot, I just topped your account for **30 mins**, transaction ID `77116030`, total time was 139 hours and 31 mins... +30 added to your rating, current score is: [+30](http://www.netbout.com/b/36421?open=rating)
