### ISSUE TITLE
Checkstyle validator prohibits clean if-else statements

### ISSUE THREAD

**Issue by rfqu** [yegor256/takes#550]
what's wrong with this code:
        InputStreamReader reader;
        if (this.charset != null) {
            reader = new InputStreamReader(body, this.charset);
        } else {
            reader = new InputStreamReader(body);
        }
???
But checkstyle validator fails it in https://ci.appveyor.com/project/yegor256/takes/build/1958 with diagnostics:
{ERROR] \src\main\java\org\takes\facets\hamcrest\HmRsBody.java[173-177]: Avoid if (x != y) ..; else ..; (ConfusingTernary)
The above if-else statement is not confusing. It is not of form  if (x != y) ..; else ..; 
I just cannot imagine how to write such statements so that validator would not complain.

**Comment by rfqu** [comment]
when I rewrite it as follows:
InputStreamReader reader =
            (this.charset != null) 
            ?
                new InputStreamReader(body, this.charset)
            :
                new InputStreamReader(body)
            ;
checker says error: Avoid inline conditionals. (AvoidInlineConditionalsCheck
Isn't it a mockery?

**Comment by rfqu** [comment]
One my method had 3 return statements. Validator said only 2 allowed. When I made 2, it said that no one allowed, return only when the method ends.

You guys go in wrong direction.

**Comment by mkordas** [comment]
@rfqu Let me explain couple of things:

> Avoid if (x != y) ..; else ..; 

 PMD demands here code like `if (this.charset == null) ...` instead of `if (this.charset != null) ...`, but `ConfusingTernary` is not present in latest Qulice anymore, so it's a matter of updating library.

> AvoidInlineConditionalsCheck

Yes, PMD prohibits ternary operators. It's rather matter of style. You can always replace them with `if`.
> One my method had 3 return statements. Validator said only 2 allowed. When I made 2, it said that no one allowed, return only when the method ends.

Again, fixed in latest Qulice version.

> You guys go in wrong direction.

I think direction is right, we just wait for @yegor256 to merge #535 and couple of things will improve. And remember, you should raise such issues in Qulice project, not here.

BTW, can you format your code in comments properly?

**Comment by davvd** [comment]
@yegor256 please dispatch this issue

**Comment by yegor256** [comment]
@rfqu read the comments from @mkordas above
