### ISSUE TITLE
Unstable Travis-CI Build

### ISSUE THREAD

**Issue by sebing** [yegor256/takes#573]
One of the builds in (https://travis-ci.org/yegor256/takes/builds/107225100) failed in java8.
Just close the PR(https://github.com/yegor256/takes/pull/551) and open again it started working.

**Comment by davvd** [comment]
@yegor256 please dispatch this issue

**Comment by davvd** [comment]
@sebing since the ticket has no milestone I set it to 1.0

**Comment by davvd** [comment]
@sebing thanks for tis bug, I topped your account for 15 mins, transaction `56b9de3f4c011657da000288`

**Comment by davvd** [comment]
@raphaelln this task is yours, please help (see our key [principles of work](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html)). If you have any technical questions, don't hesitate to ask right here... The budget of this issue is **30 mins**, which is exactly how much will be paid when the task is *done* (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by raphaelln** [comment]
@davvd just for our knowledge, I believe the above links are broken, I just get "page not found". But I already read it in the following link: http://www.yegor256.com/2014/04/17/how-xdsd-is-different.html

**Comment by davvd** [comment]
> @davvd just for our knowledge, I believe the above links are broken, I just get "page not found". But I already read it in the following link: http://www.yegor256.com/2014/04/17/how-xdsd-is-different.html
> 

@raphaelln we fixed the links, thanks

**Comment by raphaelln** [comment]
@sebing I'm not getting to reproduce this error in travis. Do you have any thoughts about how can I reproduce it ?

I put our code in my branch and I did a lot builds in travis but none of them has been failed.

Thanks.

**Comment by sebing** [comment]
@raphaelln I feel, the problem is quite random. I got the problem one more time. You can find the detail here (https://travis-ci.org/yegor256/takes/builds/108122499).

**Comment by raphaelln** [comment]
@sebing  the error above https://travis-ci.org/yegor256/takes/builds/108122499 happened in java 7, I believe this error is not related wit this one.

@davvd I don't know how to proceed to resolve this issue, I tried to simulate a lot of times, but the error not occurred. 

I searched in the build history and this error occurred in the following builds:

https://travis-ci.org/yegor256/takes/jobs/107225101
https://travis-ci.org/yegor256/takes/jobs/107225101
https://travis-ci.org/yegor256/takes/jobs/97848053

So, what we can do about it ? Maybe assign this issue to another person? 

Thanks.

**Comment by sebing** [comment]
@raphaelln I got the same issue again.
https://travis-ci.org/yegor256/takes/builds/108836178

**Comment by raphaelln** [comment]
@sebing this error is related with this issue #506

**Comment by raphaelln** [comment]
@sebing I believe this error is because the socket server is closed, I think in travis the lifetime=3000, is not enough to run the junit tests, I am thinking in increase the lifetime to 4000 in order to stop this errors. What do you think ?

I agree will be an arbitrary lifetime, but only testing with a new lifetime to know if the error disappear.

**Comment by sebing** [comment]
@raphaelln thank you for the clarification. You can ask the architect @yegor256 for specific change.

**Comment by raphaelln** [comment]
@sebing thanks, I'll ask him.

**Comment by raphaelln** [comment]
@yegor256 I believe the cause of this unstable errors is because the lifetime of the ServerSocket expires before the junit test ends, in local this never happened but in travis sometimes the `java.net.ConnectException: Connection refused` occurs.

I believe we can increase the lifetime of the ServerSocket in order to run this tests in travis, I would like to know what do you think ? Or maybe do you have any suggestion ?

Thanks

**Comment by davvd** [comment]
@raphaelln you're working with this ticket for the last 16 days. If it is not closed within the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle. [This article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck; -30 added to your rating, current score is: [-30](http://www.netbout.com/b/36530?open=rating)

**Comment by raphaelln** [comment]
@davvd I created the PR #621 5 days ago about this error. Also, I sent a question to @yegor256 11 days ago and I didn't receive any answer, anyway maybe this amount of time waiting for answers could decrease the time spent for fix this bug.

Thanks.

**Comment by raphaelln** [comment]
@sebing PR #621 is merged. Please review and close the ticket if everything is ok.

Thanks.

**Comment by sebing** [comment]
@raphaelln sure. Thanks

**Comment by davvd** [comment]
@ypshenychka please, review this task for compliance with our [quality rules](http://at.teamed.io/qa.html)

**Comment by ypshenychka** [comment]
@davvd Quality is good.

**Comment by davvd** [comment]
> @davvd Quality is good.

@ypshenychka thanks for the review and a good remark

**Comment by davvd** [comment]
@raphaelln paied 10 mins to @ypshenychka for QA review (payment ID is `79027167`). thanks, I just added **30 mins** to your account, payment `AP-4PH881585H317310S`, 437 hours and 11 mins spent. +30 added to your rating, at the moment it is: [+30](http://www.netbout.com/b/36530?open=rating)
