### ISSUE TITLE
Issue with Null is bad

### ISSUE THREAD

**Issue by datntvn** [yegor256/takes#615]
This line of code violate Null Is Bad guideline

https://github.com/yegor256/takes/blob/master/src/main/java/org/takes/facets/fork/FkHitRefresh.java#L159

Refer to:
http://www.yegor256.com/2014/05/13/why-null-is-bad.html

**Comment by davvd** [comment]
@yegor256 please take a look at it and dispatch (see [par.21](http://at.teamed.io/policy.html#21))

**Comment by yegor256** [comment]
@datntvn I believe you're talking about this line: https://github.com/yegor256/takes/blob/master/src/main/java/org/takes/facets/fork/FkHitRefresh.java#L150 Yes, it's a bad thing to use NULL, but sometimes there is no other choice, because we're dealing with JDK that has NULL in many places. So, it's an inevitable evil in this particular case. We can't fix it.
