### ISSUE TITLE
toString() implementation for logging

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/takes#88]
We need to implement toString() for all classes which will be loggable via org.takes.facets.slf4j(#28).  Moreover for classes which used as parameters.
Maybe could be use @lombok.ToString?

**Comment by yegor256** [comment]
@dmzaytsev please reformat the ticket so that it starts sound like a bug, see http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html#5.-report-when-it-is-broken

**Comment by dmzaytsev** [comment]
I expect that this code 

    Take take  = new TkText("test");
    System.out.println(String.format("%s act() return %s", take, take()));

prints something like this
`TkText(body=test) act () return RsText(body=test)`
But it prints
`[org.takes.tk.TkText@61f8bf5a] #act() return [org.takes.rs.RsText@7b49d002]`

I guess the lack toString() is the reason.

This applies to all classes which will be loggable via org.takes.facets.slf4j(#28).

**Comment by yegor256** [comment]
@dmzaytsev this description of the problem is better than you original ticket description. But still, you should say what you _need_, not what we should do in order to satisfy your needs. You should say what is _broken_. In this particular ticket, I would say something like: "I expect each class to be able to convert itself to a loggable string, but they don't have this feature". It's up to "us", whether to give you toString() or some other mechanism. See my point?

**Comment by dmzaytsev** [comment]
I'll create another ticket
