### ISSUE TITLE
Let's update Copyright notice to 2019

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/takes#925]
Let's update Copyright notice to 2019.

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by fabriciofx** [comment]
Let's wait for [zold-io/java-api#87](https://github.com/zold-io/java-api/issues/87).

**Comment by paulodamaso** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/takes/issues/925#issuecomment-453606166))

@paulodamaso Job [#925](https://github.com/yegor256/takes/issues/925) is now in scope, role is `DEV`

**Comment by paulodamaso** [comment]
@0crat assign me

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/yegor256/takes/issues/925#issuecomment-453607300))

@paulodamaso @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) not enough funds available in the project, can't set budget of job [#925](https://github.com/yegor256/takes/issues/925), see [§21](http://www.zerocracy.com/policy.html#21); @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Job [#925](https://github.com/yegor256/takes/issues/925) is not in the agenda of @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), can't retrieve data and time of add

**Comment by 0crat** [comment]
The job [#925](https://github.com/yegor256/takes/issues/925) is now out of scope
