### ISSUE TITLE
RsGzip incorrectly compresses binary data

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#96]

**Comment by yegor256** [comment]
@rultor release, tag is `0.10.1`

**Comment by davvd** [comment]
@yegor256 the task is yours (budget is 30 mins)

**Comment by davvd** [comment]
@yegor256 thank you for the ticket reported, I topped your account for 15 mins, transaction `000-f45336be`

**Comment by yegor256** [comment]
@rultor release, tag is `0.10.1`

**Comment by davvd** [comment]
@elenavolokhova please, let us know what do you think about this ticket, according to our [QA rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment]
@yegor256
According to our [quality rules](http://www.teamed.io/qa.html): 
>Problem reporter and problem solver are two different persons.

This was not a case in this ticket. Please, try to avoid such situation in future.

>Ticket title and description clearly state what is broken and what kind of fix is expected
There is no description provided. Please, update it for future reference.

**Comment by yegor256** [comment]
@elenavolokhova description updated. You're right about the "same person" problem, I'll try to avoid that in the future

**Comment by elenavolokhova** [comment]
@yegor256 Thank you!

**Comment by elenavolokhova** [comment]
@davvd Ticket passed QA review. Quality is acceptable.

**Comment by davvd** [comment]
@yegor256 10 mins was added to the account of @elenavolokhova (for QA review), in transaction 54661728; Thanks so much! Your account was topped up for **1 hour** (transaction ID is `000-4379c4ea`, the task took 13 hours and 3 mins); age=5, that's why a bonus here for fast delivery; +60 added to your rating, current score is: [+8598](http://www.netbout.com/b/35008?open=rating)
